### ISSUE TITLE
No Request Body Causes Issues with openapi-generator

### ISSUE THREAD

**Issue by jimktrains** [allengrant/shopify_openapi#1]
When running `openapi-generator-cli generate -g php -i shopify_openapi.yaml -o src` I get the following errors due to there being no schema for the request body.

```
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] WARN  o.o.c.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: php (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'php' is considered stable.
[main] INFO  o.o.c.languages.AbstractPhpCodegen - Environment variable PHP_POST_PROCESS_FILE not defined so the PHP code may not be properly formatted. To define it, try 'export PHP_POST_PROCESS_FILE="/usr/local/bin/prettier --write"' (Linux/Mac)
[main] INFO  o.o.c.languages.AbstractPhpCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' (OAS 2.0) or 'servers' (OAS 3.0) not defined in the spec. Default to [http://localhost] for server URL [http://localhost/]
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: class Tag {
    name: access
    description: null
    externalDocs: null
}
  Operation: deprecated_202001_create_storefront_access_tokens
  Resource: post /admin/api/2020-01/storefront_access_tokens.json
  Schemas: {}
  Exception: Request body cannot be null. Possible cause: missing schema in body parameter (OAS v2): class RequestBody {
    description: null
    content: class Content {
        {application/json=class MediaType {
            schema: null
            examples: {example1=class Example {
                summary: Create a new storefront access token
                description: null
                value: {"storefront_access_token":{"title":"Test"}}
                externalValue: null
                $ref: null
            }, example2=class Example {
                summary: Generating a token for an app that lacks required unauthenticated scopes fails
                description: null
                value: {"storefront_access_token":{"title":"Test"}}
                externalValue: null
                $ref: null
            }, example3=class Example {
                summary: Creating a token after exceeding the limit fails
                description: null
                value: {"storefront_access_token":{"title":"Token"}}
                externalValue: null
                $ref: null
            }}
            example: null
            encoding: null
        }}
    }
    required: null
}
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1204)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1098)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:556)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1008)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:431)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Caused by: java.lang.RuntimeException: Request body cannot be null. Possible cause: missing schema in body parameter (OAS v2): class RequestBody {
    description: null
    content: class Content {
        {application/json=class MediaType {
            schema: null
            examples: {example1=class Example {
                summary: Create a new storefront access token
                description: null
                value: {"storefront_access_token":{"title":"Test"}}
                externalValue: null
                $ref: null
            }, example2=class Example {
                summary: Generating a token for an app that lacks required unauthenticated scopes fails
                description: null
                value: {"storefront_access_token":{"title":"Test"}}
                externalValue: null
                $ref: null
            }, example3=class Example {
                summary: Creating a token after exceeding the limit fails
                description: null
                value: {"storefront_access_token":{"title":"Token"}}
                externalValue: null
                $ref: null
            }}
            example: null
            encoding: null
        }}
    }
    required: null
}
	at org.openapitools.codegen.DefaultCodegen.fromRequestBody(DefaultCodegen.java:5697)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:3525)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1172)
	... 6 more
```

**Comment by allengrant** [comment]
That's interesting. I've added schemas to the request bodies. This isn't against the OpenAPI spec. This must be an issue with the library. Regardless, fixed for you.

**Comment by AlirezaMaddah** [comment]
This issue still exists. I'm using openapi-generator-cli 6.0.1. I resolved it by adding an empty schema to request body parameters.

**Comment by Lizzergas** [comment]
I am receiving similar issue with Kotlin

**Comment by helloworld121** [comment]
Hi @allengrant, I am having the same problem using spring-boot generator.
